const FORM_STATUS_ADD = 1, FORM_STATUS_MODIFY = 2, FORM_STATUS_DELETE = 0, FORM_STATUS_NO_CHANGE = 3;
const FORMSTATUS = Object.freeze({
    Add: FORM_STATUS_ADD,
    Modify: FORM_STATUS_MODIFY,
    Delete: FORM_STATUS_DELETE,
    NoChange: FORM_STATUS_NO_CHANGE
})
export default FORMSTATUS;